config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'books/search' => 'books#search'
  get 'books/count/search' => 'books#count_search'
  resources :books, only: [:index, :create, :show, :edit, :destroy, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :searches, only: [:index] 
  get 'searches/search'
  # post 'searches/search'
  resources :notifications, only: :index
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  resources :groups do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  resources :tags do 
  end
  # post 'books/tags/search', to: 'books#search'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  attachment :image
  validates :name, presence: true
  validates :introduction, presence: true
  def joined_by?(user)
    group_users.where(user_id: user.id).exists?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end
  def index
    @new_book = current_user.books.new
    @groups = Group.all
  end
  def create
    group = Group.new(group_params)
    group.save
    group_users = GroupUser.new(group_id: group.id, user_id: current_user.id)
    group_users.save
    # binding.pry
    redirect_to groups_path
  end
  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end
  def destroy
  end
  def show
    @group = Group.find(params[:id])
    @group_user = GroupUser.where(:group_id => @group.id)
    # binding.pry

    @new_book = current_user.books.new
  end
  def edit
    @group = Group.find(params[:id])
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    AdminMailer.send_mail(@mail_title, @mail_content, group_users).deliver

  end


  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image, :owner_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Group編集</h2>
    <%= form_with model: @group, local:true do |f| %>
      <%= render 'books/error', new_book: @group %>
        <%= f.hidden_field :owner_id, :value => current_user.id  %>
      <div class="form-group">
        <%= f.label "グループ名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "紹介文" %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "グループ画像" %>
        <%= f.attachment_field :image, class: "form-control-file" %>
      </div>
      <div class="form-group">
         <%= f.submit 'Update Group', class: "btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'books/new', new_book: @new_book, user: current_user %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Group一覧</h2>
    <% if @groups.present? %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td><%= attachment_image_tag group, :image, :fill, 40, 40, fallback: "no_image.jpg" %></td>
              <td><%= link_to group.name, group_path(group.id) %></td>
              <td><%= group.introduction %></td>
              <td><%= group.group_users.count %>人</td>
              <% if group.owner_id.to_i == current_user.id%>
                <td><%= link_to "Edit", edit_group_path(group.id), class: "btn btn-sm btn-success" %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h3>グループはまだ作成されていません</h3>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Group作成</h2>
    <%= form_with model: @group, local:true do |f| %>
      <%= render 'books/error', new_book: @group %>
        <%= f.hidden_field :owner_id, :value => current_user.id  %>
      <div class="form-group">
        <%= f.label "グループ名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "紹介文" %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "グループ画像" %>
        <%= f.attachment_field :image, class: "form-control-file" %>
      </div>
      <div class="form-group">
         <%= f.submit 'Create Group', class: "btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2><%=@group.name %>メンバーへのメール</h2>
      <%= form_with url: group_send_mail_path(@group),method: :get, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :mail_title,class:'form-control'%>
        </div>
        <div class="form-group">
          <%=f.label:content %>
          <%= f.text_area :mail_content,class:'form-control' %>
        </div>
        <div>
          <%= f.submit'送信', class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <h3 class="margin_top text-center">送信が完了しました</h3>
  <div class="main_width">
    <div class="margin_top">内容は以下の通りです。</div>
      <div class="small_margin_top">
        [タイトル]<p class="font-weight-bold"> <%= @mail_title %></p>
      </div>
      <div>
        [本文]<p class="font-weight-bold"> <%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'books/new', new_book: @new_book, user: current_user %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Group詳細</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>グループ名</th>
          <th>紹介文</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= attachment_image_tag @group, :image, :fill, 40, 40, fallback: "no_image.jpg" %></td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>
            <% @group_user.each do |gu| %>
              <%= gu.user.name %><br>
            <% end %>
          </td>
          <% if @group.owner_id.to_i == current_user.id%>
            <td><%= link_to "Edit", edit_group_path(@group.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Mail', group_new_mail_path(@group), class: "fas fa-paper-plane" %></td>
          <% else %>
            <td>
              <% if @group.joined_by?(current_user)%>
                <%= link_to "Leave this Group", group_group_users_path(@group), method: :delete, class: "btn btn-sm btn-danger" %>
              <% else %>
                <%= link_to "Join this Group", group_group_users_path(@group), method: :post, class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>