config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'books/search' => 'books#search'
  get 'books/count/search' => 'books#count_search'
  resources :books, only: [:index, :create, :show, :edit, :destroy, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :searches, only: [:index] 
  get 'searches/search'
  # post 'searches/search'
  resources :notifications, only: :index
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  resources :groups do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  resources :tags do 
  end
  # post 'books/tags/search', to: 'books#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed 
  has_many :follower_user, through: :followed, source: :follower
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction,length: { maximum: 50 }
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :group_users, dependent: :destroy

  def follow(user)
    follower.create(followed_id: user.id)
  end

  def unfollow(user)
    follower.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @all_users = User.all
    @new_book = current_user.books.new
  end
  
  def show
    @user = User.find(params[:id])
    @new_book = @user.books.new
    @all_books = @user.books.all
    
    @book_count = 0
    @show = "hidden"
    # 現在ログイン中のユーザーのエントリー情報を取得
    @currentUserEntry=Entry.where(user_id: current_user.id)
    # 他ユーザーのエントリー情報を取得
    @userEntry=Entry.where(user_id: @user.id)
    # 現在ログイン中の詳細画面でない場合
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          # 現在ログイン中のユーザーと訪問先のユーザーのルームIDが同じの場合
          if cu.room_id == u.room_id then
            # ルームへの入室許可を出す
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      # まだルームIDが発行されていない場合
      unless @isRoom
        # 新しくルームとエントリー情報を作成する
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end
  
  def after_sign_up_path_for(resource)
    redirect_to user_path(resource), notice: "Welcome! You have signed up successfully."
  end
  
  def follows
    @new_book = current_user.books.new
    @user = User.find(params[:id])
    @users = @user.following_user
  end

  def followers
    @new_book = current_user.books.new
    @user = User.find(params[:id])
    @users = @user.follower_user
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def count_set
    @today = post_count((Date.today).in_time_zone.all_day)
    @yesterday = post_count((Date.today - 1).in_time_zone.all_day)
    @this = post_count(1.week.ago.beginning_of_day..Time.zone.now.end_of_day)
    @last = post_count(2.week.ago.beginning_of_day..(Date.today - 7).end_of_day)
    @dod = day_over_day_changes(@today,@yesterday)
    @wow = week_over_week_changes(@this,@last)
  end

  def post_count(date)
    return current_user.books.where(created_at: date).count
  end
  
  def day_over_day_changes(today,yesterday)
    if yesterday != 0
      return number_to_percentage((today / yesterday.to_f) * 100, precision:0)
    else
      return number_to_percentage(0, precision:0)
    end
  end
  def week_over_week_changes(this, last)
    if last != 0
      return number_to_percentage((this / last.to_f) * 100, precision:0)
    else
      return number_to_percentage(0, precision:0)
    end
  end

  def book_post_7days
    @date = []
    @count = []
    for num in 0..6 do
      day = num.day.ago.all_day
      if day == Date.today.all_day
        d = "今日"
      else
        d = num.to_s + "日前"
      end
      result = post_count(day)
      @date.push(d)
      @count.push(result)
    end
  end
end

app/views/users/_list.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td>
          <div id="follow_btn_<%= user.id %>">
            <%= render partial: 'relationships/follow-btn', locals: { user: user} %>
          </div>
        </td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local:true do |f| %>
      <%= render 'books/error', new_book: @user %>
      <div class="form-group">
        <%= f.label:Name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label:Image %>
        <%= f.attachment_field :profile_image, class: "form-control-file" %>
      </div>
      <div class="form-group">
        <%= f.label:Introduction %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-group">
         <%= f.submit 'Update User', class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'books/new', new_book: @new_book, user: @user %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Followers</h2>
    <%= render 'list', users: @users %>
  </div>
</div>

app/views/users/follows.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'books/new', new_book: @new_book, user: @user %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Follows</h2>
    <%= render 'list', users: @users %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'searches/search' %>
<div class="row">
  <div class="col-md-3">
    <%= render 'books/new', new_book: @new_book, user: current_user %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <% if current_user %>
      <%= link_to "グループを作成", new_group_path %> |
      <%= link_to "グループ一覧", groups_path %>
    <% end %>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @all_users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td>フォロー数：<%= user.follower.count %></td>
            <td>フォロワー数：<%= user.followed.count %></td>
            <td>
              <div id="follow_btn_<%= user.id %>">
                <%= render partial: 'relationships/follow-btn', locals: { user: user} %>
              </div>
            </td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'searches/search' %>
<div class="row">
  <div class="col-md-3">
    <%= render 'books/new', new_book: @new_book, user: @user %>
    <%= link_to "通知",  notifications_path %>
    <% unless @user.id == current_user.id %>
      <% if (current_user.following?(@user) && (@user.following?(current_user))) %>
        <% if @isRoom == true %>
          <%= link_to "チャットへ", room_path(@roomId) %>
        <% else %>
          <%= form_with model: @room do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, :value => @user.id %>
            <% end %>
            <%= f.submit "チャットを始める" %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div class="col-md-8 offset-md-1">
    <%= render 'books/list', all_books: @all_books %>
    <h4>投稿数の前日比・前週比</h4>
    <% count_set %>
    <table class="post_count_table">
      <tr>
        <th>今日の投稿数</th>
        <th>前日の投稿数</th>
        <th>前日比</th>
      </tr>
      <tr>
        <td><%= @today %></td>
        <td><%= @yesterday %></td>
        <td><%= @dod %></td>
      </tr>
    </table>
    <table class="post_count_table">
      <tr>
        <th>今週の投稿数</th>
        <th>先週の投稿数</th>
        <th>前週比</th>
      </tr>
      <tr>
        <td><%= @this %></td>
        <td><%= @last %></td>
        <td><%= @wow %></td>
      </tr>
    </table>

    <div>
      <% book_post_7days %>
      <h4>7日間分の投稿数</h4>
      <table class="post_7days_table">
        <tr>
          <% @date.reverse.each do |d| %>
            <th><%= d %></th>
          <% end %>     
        </tr>
        <tr>
          <% @count.reverse.each do |cnt| %>
            <td><%= cnt %></td>
          <% end %>     
        </tr>
      </table>
    </div>
    <div>
      <canvas id="myChart"></canvas>
    </div>
    <div>
      <%= form_with(url: books_count_search_path, method: :get, remote:true) do |f| %>
        <%= f.date_field :sample_at, class: "form-control" %>
        <%= f.submit '検索', class: "btn btn-success" %>
      <% end %>
      <div id="search_result">
        <%= render partial: "books/count_search", locals: { book_count: @book_count, show: @show} %>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).on('turbolinks:load', function() {
  var ctx = document.getElementById("myChart");
  var myChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: ['6日前','5日前','4日前','3日前','2日前','1日前','今日',],
      datasets: [
        {
          yAxisID: 'yaxes_1',
          label: '投稿した本の数',
          data: <%= @count.reverse %>,
          borderColor: "rgba(0,0,255,1)",
          backgroundColor: "rgba(0,0,0,0)",
          lineTension: 0.5,
        }]
    },
    options: {
      plugins: {
        title: {
          display: true,
          text: '7日間分の投稿数'
        }
      },
      scale: {
        "yaxes_1": {
          display: true,
          min: 0,
          max: 10,
          ticks: {
            stepSize: 1 
          } 
        }
      }
    }
  });
  });
</script>