config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get 'books/search' => 'books#search'
  get 'books/count/search' => 'books#count_search'
  resources :books, only: [:index, :create, :show, :edit, :destroy, :update, :destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  resources :searches, only: [:index] 
  get 'searches/search'
  # post 'searches/search'
  resources :notifications, only: :index
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  resources :groups do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  resources :tags do 
  end
  # post 'books/tags/search', to: 'books#search'
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :notifications, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  is_impressionable counter_cache: true
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def create_notification_favorite!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and book_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        book_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, book_comment_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      book_id: id,
      book_comment_id: book_comment_id,
      visited_id: user_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  def save_tag(sent_tag)
    new_book_tag = Tag.find_or_create_by(tag_name: sent_tag)
    self.tags << new_book_tag
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  impressionist :actions=> [:show], unique: [:impressionable_id, :ip_address]
  def index
    @all_users = User.all
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    # @all_books = Book.includes(:favorited_users).
    #   sort {|a,b| 
    #     b.favorited_users.includes(:favorites).where(created_at: from...to).size <=> 
    #     a.favorited_users.includes(:favorites).where(created_at: from...to).size
    #   }

    if (params[:sort] == "new_list")
      @all_books = Book.all.order(created_at: "DESC")
    elsif (params[:sort] == "rank_list")
      @all_books = Book.all.order(evaluation: "DESC")
    else
      @all_books = Book.includes(:user,:book_comments,:favorites,:notifications,:tags,:impressions)
    end    
    # @users = User.includes(:books, :favorites, :book_comments, :follower, :followed, :active_notifications, :passive_notifications, :messages, :entries, :group_users)
    # @user = @users.find(current_user.id)
    # binding.pry
    @new_book = current_user.books.new
  end
  
  def show
    @user = Book.find(params[:id]).user
    @new_book = current_user.books.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    impressionist(@book, nil, unique: [:impressionable_id, :ip_address])
    # binding.pry
    redirect_to books_path if @book.blank?
  end
  
  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    tag_list = params[:book][:tag_name]
    if @new_book.save
      @new_book.save_tag(tag_list)
      redirect_to book_path(@new_book.id), notice: "You have created book successfully."
    else
      @all_books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  def search
    @new_book = current_user.books.new
    @tag = Tag.find_by(tag_name: params[:tag_name])
    if @tag.nil?
      redirect_to books_path
    else
      @all_books = @tag.books
      render :index  
    end
  end

  def count_search
    date = params[:sample_at].in_time_zone.all_day
    @book_count = current_user.books.where(created_at: date).count
    @show = "show"
    # binding.pry
    # redirect_back(fallback_location: root_path)
  end

  private
  
  def book_params
    params.require(:book).permit(:title, :body, :evaluation)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_count_search.html.erb
<div class="<%= show %>">
  <h4>検索結果</h4>
  <th>投稿数</th>
  <td><%= book_count %></td>
</div>

app/views/books/_error.html.erb
<% if new_book.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= new_book.errors.count %>errors prohibited this book from being saved:
    </h2>
    <ul>
      <% new_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_list.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Rate</th>
      <th>Tag</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% all_books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td class="book-evaluation" data-score="<%= book.evaluation %>"></td>
        <td>
          <% book.tags.each do |tag| %>
            <%= link_to tag.tag_name, books_search_path(tag_name: tag.tag_name), method: :get %><br>
          <% end %>
        </td>
        <% if book.user != current_user %>
          <td>
            <div id="favorite_btn_<%= book.id %>">
               <%= render partial: 'favorites/favorites-btn', locals: { book: book} %>
            </div>
          </td>
        <% end %>
        <td>コメント数: <%= book.book_comments_count %></td>
        <td>閲覧数：<%= book.impressionist_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>  
<script>
  $('.book-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/books/_new.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "profile_image" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
	    <th>name</th>
	    <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
	    <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
	    <th>
	      <%= link_to user.follower.count, follows_user_path(user) %>
	    </th>
    </tr>
    <tr>
      <th>followers</th>
	    <th><%= link_to user.followed.count, followers_user_path(user) %></th>
    </tr>
    <tr>
      <th>
        <div id="follow_btn_<%= user.id %>">
          <%= render partial: 'relationships/follow-btn', locals: { user: user} %>
        </div>
      </th>
    </tr>
  </tbody>
</table>
<%= form_with model: new_book, local:true do |book| %>
  <table>
    <div class="row">
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>
    <h2 class="mt-3">New book</h2>
      <div class="form-group">
        <% if new_book.errors.added?(:title, :blank) %>
          <div class="field_with_errors">
            <%= book.label:Title %>
          </div>
          <%= book.text_field :title, class: "form-control" %>
        <% else %>
          <%= book.label:Title %>
          <%= book.text_field :title, class: "form-control" %>
        <% end %>
      </div>
      <div class="form-group">
        <% if new_book.errors.added?(:body, :blank) %>
          <div class="field_with_errors">
            <%= book.label:Opinion %>
          </div>
          <%= book.text_area :body, class: "form-control" %>
        <% else %>
          <%= book.label:Opinion %>
          <%= book.text_area :body, class: "form-control" %>
        <% end %>
      </div>
      <div id="evaluate_stars">
        <label>Rate</label>
      </div>
      <div class="form-group">
        <%= book.label:Tag %>
        <%= book.text_field :tag_name, class: "form-control" %>        
      </div>
      <div class="form-group">
        <%= book.submit 'Create Book', class: "btn btn-success" %>
      </div>
  </table>
<% end %>
<script>
  $('#evaluate_stars').raty({
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    scoreName: 'book[evaluation]', //登録するモデル名とカラム名を記述
    half: true
  });
</script>

app/views/books/count_search.js.erb
$('#search_result').html("<%= j(render partial: 'books/count_search', locals: {book_count: @book_count, show: @show}) %>");

app/views/books/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>
    <%= form_with model: @book, local: true do |f| %>
      <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= @book.errors.count %>errors prohibited this book from being saved:
        </h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="form-group">
        <div class="field">
          <%= f.label:Title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label:Opinion %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="field">
          <%= f.label:Rate %>
          <div class="book-evaluation" data-score="<%= @book.evaluation %>"></div>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit 'Update Book', class: "btn btn-success" %>
      </div>
    <% end %>
    <%= link_to "Show", book_path(@book) %>
     |  
    <%= link_to "Back", books_path %>
  </div>
</div>
<script>
  $('.book-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/books/index.html.erb
<%= render 'searches/search' %>
<%= render 'books/error', new_book: @new_book %>
<div class="row">
  <div class="col-md-3">
    <%= render 'books/new', new_book: @new_book, user: current_user %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <%= link_to "新着順", books_path(sort: "new_list") %> |
    <%= link_to "評価順", books_path(sort: "rank_list") %>
    <%= render 'books/list', all_books: @all_books %>
  </div>
</div>

app/views/books/search.html.erb
<h1>サーチだよ！！！</h1>

app/views/books/show.html.erb
<%= render 'searches/search' %>
<div class="row">
  <div class="col-md-3">
    <%= render 'books/new', new_book: @new_book, user: @user %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th>Rate</th>
          <th>Tag</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <%= link_to user_path(@book.user.id) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %><br>
              <%= link_to @book.user.name, user_path(@book.user.id) %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <td class="book-evaluation" data-score="<%= @book.evaluation %>"></td>
          <td>
            <% @book.tags.each do |tag| %>
              <%= link_to tag.tag_name, books_search_path(tag_name: tag.tag_name), method: :get %><br>
            <% end %>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか?", class: "btn btn-sm btn-danger" %></td>
          <% end %>
          <td>
            <div id="favorite_btn_<%= @book.id %>">
              <%= render partial: 'favorites/favorites-btn', locals: { book: @book} %>
            </div>
          </td>
          <td>
            <div id="comment_count_<%= @book.id %>">
              <%= render partial: 'book_comments/comment-count', locals: { book: @book} %>            
            </div>
          </td>
          <td>
            閲覧数：<%= @book.impressionist_count %>
          </td>
        </tr>
      </tbody>
    </table>
    <div id="comment_btn_<%= @book.id %>">
      <%= render partial: 'book_comments/book-comment', locals: { book: @book, book_comment: @book_comment} %>
    </div>
  </div>
</div>
<script>
  $('.book-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>